### ISSUE TITLE
请教单机多卡训练问题

### ISSUE THREAD

**Issue by pkuwudi** [alibaba/graph-learn#125]
您好，我想在单机上用多张显卡训练deepwalk模型，请问有没有可以参考的单机多卡训练代码实例，希望能得到您的指点，不胜感激。

**Comment by baoleai** [comment]
Sorry, 目前没有提供这样的示例，需要你自己来基于deepwalk代码修改成单机多卡的模型。目前提供的分布式示例也只是数据并行的实现，参考graphsage。谢谢~

在 2020/12/1，pkuwudi<notifications@github.com> 写道：

**Comment by pkuwudi** [comment]
> Sorry, 目前没有提供这样的示例，需要你自己来基于deepwalk代码修改成单机多卡的模型。目前提供的分布式示例也只是数据并行的实现，参考graphsage。谢谢~ 在 2020/12/1，pkuwudi<notifications@github.com> 写道：
> […](#)
> 您好，我想在单机上用多张显卡训练deepwalk模型，请问有没有可以参考的单机多卡训练代码实例，希望能得到您的指点，不胜感激。 -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #125



> Sorry, 目前没有提供这样的示例，需要你自己来基于deepwalk代码修改成单机多卡的模型。目前提供的分布式示例也只是数据并行的实现，参考graphsage。谢谢~ 在 2020/12/1，pkuwudi<notifications@github.com> 写道：
> […](#)
> 您好，我想在单机上用多张显卡训练deepwalk模型，请问有没有可以参考的单机多卡训练代码实例，希望能得到您的指点，不胜感激。 -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #125



> Sorry, 目前没有提供这样的示例，需要你自己来基于deepwalk代码修改成单机多卡的模型。目前提供的分布式示例也只是数据并行的实现，参考graphsage。谢谢~ 在 2020/12/1，pkuwudi<notifications@github.com> 写道：
> […](#)
> 您好，我想在单机上用多张显卡训练deepwalk模型，请问有没有可以参考的单机多卡训练代码实例，希望能得到您的指点，不胜感激。 -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #125

感谢您的回复！

**Comment by pkuwudi** [comment]
感谢您的回复

**Comment by pkuwudi** [comment]
> Sorry, 目前没有提供这样的示例，需要你自己来基于deepwalk代码修改成单机多卡的模型。目前提供的分布式示例也只是数据并行的实现，参考graphsage。谢谢~ 在 2020/12/1，pkuwudi<notifications@github.com> 写道：
> […](#)
> 您好，我想在单机上用多张显卡训练deepwalk模型，请问有没有可以参考的单机多卡训练代码实例，希望能得到您的指点，不胜感激。 -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #125

感谢您的回复！
