### ISSUE TITLE
[BUG] 对‘_ULx86_64_step’未定义的引用

### ISSUE THREAD

**Issue by jingmouren** [alibaba/graph-learn#143]
cmake 时报如下错误

/git/alibaba/graph-learn/built/lib/libgraphlearn_shared.so：对‘_ULx86_64_step’未定义的引用
/git/alibaba/graph-learn/built/lib/libgraphlearn_shared.so：对‘_ULx86_64_get_reg’未定义的引用
/git/alibaba/graph-learn/built/lib/libgraphlearn_shared.so：对‘_Ux86_64_getcontext’未定义的引用
/git/alibaba/graph-learn/built/lib/libgraphlearn_shared.so：对‘gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)’未定义的引用
/git/alibaba/graph-learn/built/lib/libgraphlearn_shared.so：对‘_ULx86_64_init_local’未定义的引用
collect2: error: ld returned 1 exit status
make[2]: *** [../built/bin/service_unittest] 错误 1
make[1]: *** [CMakeFiles/service_unittest.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by sighingnow** [comment]
Hi @jingmouren, I have transfer the issue to the graph-learn repo: https://github.com/alibaba/graph-learn/issues/143

And I'm going to close this ticket. Free to reopen if you have any other questions.

**Comment by jingmouren** [comment]
不过 libunwind-devel and gflags-devel 已经装了。还是报这错

**Comment by jackonan** [comment]
@jingmouren 不同环境编译方式可能有差异，手动改一下Makefile，在so编译时加上-lunwind
