### ISSUE TITLE
如何使用pytorch编写GNN模型，该如何处理EgoGraph？

### ISSUE THREAD

**Issue by Ningsir** [alibaba/graph-learn#147]

**Comment by jackonan** [comment]
EgoGraph是模型相关的，目前模型层接口只内置了TF的实现，没有PyTorch。如果用PyTorch，可以用GSL返回的数据，自己实现后续部分。GraphLearn 2.0接口也正在发布的路上，届时接口会更清晰易懂。

**Comment by baoleai** [comment]
https://graph-learn.readthedocs.io/en/latest/algo/torch/index.html
