### ISSUE TITLE
gl.LearningBasedModel  raise AttributeError: 'module' object has no attribute 'LearningBasedModel'

### ISSUE THREAD

**Issue by pangedeshijie** [alibaba/graph-learn#148]
"from graphlearn.python.models import *" command can be imported normally, 
but "import graphlearn as gl && gl.module" will raise AttributeError: 
'module' object has no attribute 'LearningBasedModel'

**Comment by jackonan** [comment]
Sorry to trouble you. The current interfaces is a little confused sometimes. We will release the latest version soon.

**Comment by tashengjinsheng** [comment]
> Sorry to trouble you. The current interfaces is a little confused sometimes. We will release the latest version soon.

Is this problem solved?

**Comment by miziha-zp** [comment]
> Sorry to trouble you. The current interfaces is a little confused sometimes. We will release the latest version soon.

anything update？

**Comment by baoleai** [comment]
This class is in old version r0.4.0. We recommend you to use the latest version.
