### ISSUE TITLE
Save embeddings out of sync when deepwalk distributed training

### ISSUE THREAD

**Issue by Memz99** [alibaba/graph-learn#149]
I tried the way in https://github.com/alibaba/graph-learn/issues/53 that "you can put `get_node_embedding` in `train` funciton before session run in `trainer.py`" in deepwalk dist training.  

With 4 ps and 16 worker in my case, the embedding variables are fixed partitioned on 4 ps. When saving embedding via `get_node_embedding()`, I found each worker just saved its own nodes embedding part. But each worker's training time can be different, it may save the embedding too early before other worker done. (in my case, some workers cost 30min and some in 10mins.)

Is there a better way to save embedding in deepwalk dist training?

**Comment by jackonan** [comment]
Different workers will consume different graph partitions, which may cause unbalanced data. GL utilizes Vertex/Edge id as the partition key. You can check your data to figure out whether unbalanced problem existed.

**Comment by baoleai** [comment]
fixed in v1.0.0, https://github.com/alibaba/graph-learn/blob/master/examples/tf/trainer.py#L64
