### ISSUE TITLE
aggregator: C++ version vs Python version

### ISSUE THREAD

**Issue by cozilla** [alibaba/graph-learn#15]
I find graph-learn has aggregator with both c++ and python version (`mean`, `sum`...).
Why Graph-Learn need c++ version `aggregator`?

**Comment by Seventeen17** [comment]
C++ version aggregator is a WIP feature, which can reduce the communication overhead with distribution mode and reduce the memcopy of C ++ to numpy.
And with aggregation pushed down to sampler workers, the acceleration of aggregation with different devices is being considered.

**Comment by patricxu** [comment]
Could you provide more demo for C++ extensions？ @Seventeen17

**Comment by cozilla** [comment]
> C++ version aggregator is a WIP feature, which will be an optimization of python version.

Thanks. It seems network optimization. Rather than sending all feature back, it only returns aggregated values. Such optimization looks works for simple aggregator (mean/sum/max..). If aggregator is trainable, it's hard to optimize.

**Comment by Seventeen17** [comment]
> > C++ version aggregator is a WIP feature, which will be an optimization of python version.
> 
> Thanks. It seems network optimization. Rather than sending all feature back, it only returns aggregated values. Such optimization looks works for simple aggregator (mean/sum/max..). If aggregator is trainable, it's hard to optimize.

Yes, that's right. Only the interchangeable aggregators will work, and aggregator like `LSTM` is not the target of optimization in this feature.

**Comment by cozilla** [comment]
appreciate your quick response :)
