### ISSUE TITLE
how to start ?

### ISSUE THREAD

**Issue by ucasiggcas** [alibaba/graph-learn#154]
hi,dear
when I run 
`$ python cora.py`
Traceback (most recent call last):
  File "cora.py", line 26, in <module>
    from utils import download, extract
  File "/data/prod/xulm1/graph-learn/examples/data/utils.py", line 24, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

how to deal with it ?
thx

**Comment by ucasiggcas** [comment]
and where is the `train_supervised.py` in the [url](https://github.com/alibaba/graph-learn/blob/master/examples/tf/graphsage/README.md)
```
Training

supervised: python train_supervised.py
unsupervised: python train_unsupervised.py
```

**Comment by ucasiggcas** [comment]
大佬，源码编译阶段出错了，按照[这里](https://github.com/alibaba/graph-learn/blob/master/docs/install_cn.md)执行，如下：
```
$ make test
prepare protobuf library ...
protobuf done
prepare grpc library ...
grpc done
prepare glog library ...
glog done
prepare gtest library ...
gtest done
graphlearn/proto/tensor.proto graphlearn/proto/request.proto graphlearn/proto/service.proto graphlearn/proto/dag.proto
/data/logs/xulm1/graph-learn/built/graphlearn/proto/tensor.pb.o /data/logs/xulm1/graph-learn/built/graphlearn/proto/request.pb.o /data/logs/xulm1/graph-learn/built/graphlearn/proto/service.pb.o /data/logs/xulm1/graph-learn/built/graphlearn/proto/dag.pb.o /data/logs/xulm1/graph-learn/built/graphlearn/proto/service.grpc.pb.o
generating pb file
/data/logs/xulm1/graph-learn/third_party/grpc/build/bin/grpc_cpp_plugin: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
Makefile:126: recipe for target 'proto' failed
make: *** [proto] Error 1

```

**Comment by baoleai** [comment]
> hi,dear
> when I run
> `$ python cora.py`
> Traceback (most recent call last):
> File "cora.py", line 26, in
> from utils import download, extract
> File "/data/prod/xulm1/graph-learn/examples/data/utils.py", line 24, in
> import urllib2
> ModuleNotFoundError: No module named 'urllib2'
> 
> how to deal with it ?
> thx

Are you using python2 or python3. The urllib2 module has been split across several modules in Python 3 named urllib.request
