### ISSUE TITLE
感觉graphlearn的graph数据管理部分做的还是比较牛皮的

### ISSUE THREAD

**Issue by eedalong** [alibaba/graph-learn#155]
话说，写数据管理这部分的工程师是不是有graphdb的背景，感觉像是写graphdb的人写的。

**Comment by baoleai** [comment]
你说的数据管理部分指的是图的存储吗？

Dalong ***@***.***> 于2021年5月13日周四 下午3:31写道：

**Comment by eedalong** [comment]
整个图的前端部分，包括存储、采样、查询这些。性能优化上虽然没有看到特别的策略，但是图的抽象这些倒挺统一的。可能和aligraph一开始就target到分布式、异构的图的处理，使得整个设计比较统一。看dgl那边就感觉设计不太统一，有点拼凑的感觉。
