### ISSUE TITLE
[QUESTION] Taobao e-commerce dataset

### ISSUE THREAD

**Issue by spapadias** [alibaba/graph-learn#158]
Hello all,

The link to the Taobao e-commerce dataset in [Aligraph](http://www.vldb.org/pvldb/vol12/p2094-zhu.pdf) VLDB paper is no longer working. Specifically, the following link: https://tianchi.aliyun.com/dataset/dataDetail?dataId=9716

Furthermore, it seems that I cannot access the aliyun dataset page at all. Do you know if it is closed and more precisely where could I find the above-mentioned e-commerce dataset?

Best and thanks,
Makis

**Comment by baoleai** [comment]
Hi, I can open the link you posted above(in China).

**Comment by spapadias** [comment]
Hi,

Could you please copy the link address here as I believe that I will be
able to do wget and successfully download it through this process.

Do you agree?

Best,
Serafeim Papadias
https://spapadias.github.io/
Research Associate @ TU Berlin

**Comment by spapadias** [comment]
Hi again,

After giving it some thought, what I propose will not make a difference.
I am in Berlin, Germany. Do you know any possible way for me to download this dataset?

Best,
Makis
