### ISSUE TITLE
differences with alibaba/euler? 

### ISSUE THREAD

**Issue by suesunss** [alibaba/graph-learn#16]
Hi,

Thanks for developing this open-source project, I noticed that alibaba also open-sourced [euler](https://github.com/alibaba/euler), can anyone point out the differences between the two ?

**Comment by patricxu** [comment]
and difference with [DGL](https://docs.dgl.ai)

**Comment by hibayesian** [comment]
and Tencent's [Plato](https://github.com/Tencent/plato)

**Comment by baoleai** [comment]
There are some excellent graph learning related framworks, but each system has its own focus. Graph-Learn is mainly for industrial large-scale heterogeneous graphs. It implements a distributed graph engine and provides a graph learning model programming framework at the upper layer to simplify the development of GNNs. When you want to try GNNs, welcome to use Graph-Learn:)

**Comment by patricxu** [comment]
@baoleai Is there any way to integrate the classical graph algorithm into GL, such as Pagerank, LPA, WCC .etc.

**Comment by sonogoto** [comment]
> @baoleai Is there any way to integrate the classical graph algorithm into GL, such as Pagerank, LPA, WCC .etc.

NO, it doesn't design for graph computing
