### ISSUE TITLE
Mac OS安装失败，缺失sem_timedwait

### ISSUE THREAD

**Issue by xiangzhijun** [alibaba/graph-learn#160]
/Users/root/graph-learn/graphlearn/core/dag/dag_dataset.cc:62:7: error: use of undeclared identifier 'sem_timedwait'
  if (sem_timedwait(&(occupied_[cursor_]), &ts) == -1) {
      ^
3 warnings and 1 error generated.

mac c不支持sem_timedwait函数，导致安装失败:
![image](https://user-images.githubusercontent.com/30745874/129169356-1e3df2d6-cdff-48ee-a2dc-4ddfb4c9a560.png)

**Comment by Seventeen17** [comment]
需要在linux上编译

**Comment by xiangzhijun** [comment]
> 欢迎贡献Mac os上的编译

Mac os编译成功了，但是examples跑不起来，各种错误

**Comment by baoleai** [comment]
Please try v1.1.0.
