### ISSUE TITLE
grpc error

### ISSUE THREAD

**Issue by Amitly** [alibaba/graph-learn#166]
![image](https://user-images.githubusercontent.com/57850373/141329781-4e67bf0d-51aa-41de-91a4-2d4f074792f6.png)
Are there any requirements for the dependent grpc version library?

**Comment by baoleai** [comment]
Please provide information about your compilation environment commands, etc.

**Comment by Amitly** [comment]
> 

![image](https://user-images.githubusercontent.com/57850373/142756157-0d67c37a-3a2f-4e4c-9092-45f8f2c4b1da.png)
我在执行make test这条指令后出现这个问题

**Comment by baoleai** [comment]
What is your compilation environment and do you get any errors after make
