### ISSUE TITLE
Can not read attribute from data file.

### ISSUE THREAD

**Issue by UnnameBao** [alibaba/graph-learn#17]
I parser my dataset to formated file like this:
node:
```
id:int64	attribute:string
3916	c
1819	c
4501	c
```
edge:
```
src_id:64	dst_id:int64	attribute:string
4	6	p
4	7	p
4	8	p
4	9	j
```
then I run commands:
```
g = g.node(source="data/graph_data/node0.txt", node_type="entry", decoder=gl.Decoder(attr_types=["string"]))
g = g.edge(source="data/graph_data/edge0.txt", edge_type = ("entry", "entry", "action"), decoder=gl.Decoder(attr_types=["string"]))
g = g.init()
```
when I tried to get node's attibute, I found it is empty:
```
In [11]: res.__dict__
Out[11]: 
{'_attred': False,
 '_float_attrs': None,
 '_graph': <graphlearn.python.graph.Graph at 0x7fc178e71d90>,
 '_ids': array([   4, 3916]),
 '_int_attrs': None,
 '_labels': None,
 '_shape': (2,),
 '_string_attrs': None,
 '_type': 'entry',
 '_weights': None}
```
Is there any step wrong?

**Comment by archwalker** [comment]
It seems correct on my machine
```
import graphlearn as gl
import numpy as np

def main():
  g = gl.Graph()
  g = g.node(source="node_table", node_type="entry", decoder=gl.Decoder(attr_types=["string"]))
  g = g.edge(source="edge_table", edge_type=("entry", "entry", "action"),
             decoder=gl.Decoder(attr_types=["string"]))
  g = g.init()
  print(g.V('entry', feed=np.array([3916])).emit(lambda v: v.string_attrs))

if __name__ == '__main__':
  main()
## return [['c']]
```
p.s. your edge table has a typo `src_id:int64`, fix it and then check if the problem still exists.

**Comment by Seventeen17** [comment]
Only when you call 

> I parser my dataset to formated file like this:
> node:
> 
> ```
> id:int64	attribute:string
> 3916	c
> 1819	c
> 4501	c
> ```
> 
> edge:
> 
> ```
> src_id:64	dst_id:int64	attribute:string
> 4	6	p
> 4	7	p
> 4	8	p
> 4	9	j
> ```
> 
> then I run commands:
> 
> ```
> g = g.node(source="data/graph_data/node0.txt", node_type="entry", decoder=gl.Decoder(attr_types=["string"]))
> g = g.edge(source="data/graph_data/edge0.txt", edge_type = ("entry", "entry", "action"), decoder=gl.Decoder(attr_types=["string"]))
> g = g.init()
> ```
> 
> when I tried to get node's attibute, I found it is empty:
> 
> ```
> In [11]: res.__dict__
> Out[11]: 
> {'_attred': False,
>  '_float_attrs': None,
>  '_graph': <graphlearn.python.graph.Graph at 0x7fc178e71d90>,
>  '_ids': array([   4, 3916]),
>  '_int_attrs': None,
>  '_labels': None,
>  '_shape': (2,),
>  '_string_attrs': None,
>  '_type': 'entry',
>  '_weights': None}
> ```
> 
> Is there any step wrong?

First, please fix the typo @archwalker mentioned.
Second, to avoid redundant queries, the attribute query and assignment of `_string_attrs`  only execute when you call `nodes.string_attrs`.

**Comment by UnnameBao** [comment]
> First, please fix the typo @archwalker mentioned.
> Second, to avoid redundant queries, the attribute query and assignment of `_string_attrs` only execute when you call `nodes.string_attrs`.

Thanks, I fix this by run two steps. It seems that both two steps needed.

**Comment by UnnameBao** [comment]
It's embarrassing to reply this issue again. But I spent a lot of time on how to use edge attribute. I read the same formated file(after fixed), this time I tried to query edge attribute:
```
res = g.E("action", feed=(np.array([4]), np.array([8]))).emit()
```

then I tried to get edge's attribute, but an error occured:
```
/usr/local/lib/python2.7/dist-packages/graphlearn/python/values.pyc in _lookup_and_set_values(self)
    438     values = self._graph.lookup_edges(self._edge_type,
    439                                       self._src_ids,
--> 440                                       self._edge_ids)
    441     self._set_values(values)
    442 

/usr/local/lib/python2.7/dist-packages/graphlearn/python/graph.pyc in lookup_edges(self, edge_type, src_ids, edge_ids)
    618     """
    619     batch_size = src_ids.flatten().size
--> 620     if batch_size != edge_ids.flatten().size:
    621       raise ValueError("src_ids and edge_ids for lookup edges must "
    622                        "be same, got {} and {}"

AttributeError: 'NoneType' object has no attribute 'flatten'
```

I tried to add edge_id col in my edge file but it still not work, this is part of my node file:
```
id:int64	attribute:string
4	a
6	c
7	c
8	c
9	c
8	c
```
this is part of my edge file:
```
src_id:int64	dst_id:int64	attribute:string
4	6	p
4	7	p
4	8	p
4	9	j
src_id:int64	dst_id:int64	attribute:string
4	6	p
4	7	p
4	8	p
4	9	j
4	9	j
```
I notice that the same group of src_id and dst_id show up servel times, but I tried to cut file and still not work.

**Comment by archwalker** [comment]
Can you post the full script you used to reproduce the problem, I have tried the code you provided above, and it works on my machine.

**Comment by Seventeen17** [comment]
Good question. 
Edge query with given `(src_ids, dst_ids)`  is not supported for now. You can only get the attributes of edges from edges that are sampled by `outE()/inE()` or generated from `E(edge_type)` with `feed=None`.

**Comment by UnnameBao** [comment]
> Good question.
> Edge query with given `(src_ids, dst_ids)` is not supported for now. You can only get the attributes of edges from edges that are sampled by `outE()/inE()` or generated from `E(edge_type)` with `feed=None`.

I work on with the frist method:
```
import graphlearn as gl
import numpy as np

g = gl.Graph()\
        .node("data/graph_data/node1.txt", node_type="entry", decoder=gl.Decoder(attr_types=["string"]))\
        .edge("data/graph_data/edge1.txt", edge_type=("entry","entry","action"), decoder=gl.Decoder(attr_types=['string']))
g = g.init()
res = g.V("entry", np.array([4])).outE("action").emit()
print(res)
res = g.V("entry", np.array([4])).outE("action").sample().by("full").emit()
print(res)
edge = res[1]
print(edge.string_attrs)
```
It seem it won't work without using "sample" or "by" method

I tried generated from E(edge_type) with feed=None but it will occur an error:
```
res = g.E("action", feed=None).emit()

Traceback (most recent call last):
  File "tmp.py", line 14, in <module>
    res = g.E("action", feed=None).emit()
  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/query.py", line 198, in emit
    gen = self.qe.parse_tree(self.query_root, func)
  File "/usr/local/lib/python2.7/dist-packages/graphlearn/python/query.py", line 444, in parse_tree
    cur_query = query_root.value
AttributeError: 'NoneType' object has no attribute 'value'
[2020-04-09 10:36:09.121174] Server stopped.
```

**Comment by Seventeen17** [comment]
`outE(edge_type)`/`outV(edge_type)`/`inE(edge_type)`/`inV(edge_type)` must be used with `sample()` and `by()`.
When using `E(edge_type)` without `feed`, you should assign the batch_size with `.batch(N)`.
