### ISSUE TITLE
This is a piece of shit

### ISSUE THREAD

**Issue by platoneko** [alibaba/graph-learn#170]
什么垃圾代码 就这还好意思开源

**Comment by YongCHN** [comment]
> 

你的这个言论完全反映了你的素质

**Comment by xiaoming-qxm** [comment]
> 什么垃圾代码 就这还好意思开源

开源是将自己觉得有用的东西跟大家分享出来，然后一群志同道合的人一起让它变得更好！

开源平台是个交流技术的地方，不是宣泄情绪的场所；

issues是用于反馈技术性问题的地方，因而我将关闭这个无关的issue

**Comment by platoneko** [comment]
做系统的还是要对计算机科学有基本的敬畏之心，而不是胡乱弄一套，相信你的这个系统没有完全反映贵司的技术水平。

**Comment by YongCHN** [comment]
> 

在学会对科学的敬畏之心之前，先建议你学学如何做人。
