### ISSUE TITLE
Could not find a version that satisfies the requirement graph-learn

### ISSUE THREAD

**Issue by Amitly** [alibaba/graph-learn#171]
![image](https://user-images.githubusercontent.com/57850373/143675729-3c564efc-40ee-4868-92a3-45a52a9b25f5.png)
操作系统：Ubuntu18.04
pip：9.0.1
python：2.7/3.6

**Comment by baoleai** [comment]
Please try `python3 -m pip install graph-learn`. You should use a newer version of pip3.

**Comment by Amitly** [comment]
> Please try `python3 -m pip install graph-learn`. You should use a newer version of pip3.

感谢，解决了这个问题！是pip版本低导致的
