### ISSUE TITLE
pip install not working 

### ISSUE THREAD

**Issue by snash4** [alibaba/graph-learn#175]
Pip install is not working. I also tried the solution you have given but I still get this error:

ERROR: Could not find a version that satisfies the requirement graph-learn (from versions: none)
ERROR: No matching distribution found for graph-learn
Please try `python3 -m pip install graph-learn`. You should use a newer version of pip3.

_Originally posted by @baoleai in https://github.com/alibaba/graph-learn/issues/171#issuecomment-981268518_

**Comment by baoleai** [comment]
What are your python and pip version? Python>=3.6 and pip >=21 are required.

**Comment by snash4** [comment]
python 3.6.13
pip 21.3.1
