### ISSUE TITLE
ImportError: cannot import name 'pywrap_graphlearn' from 'graphlearn' (unknown location)

### ISSUE THREAD

**Issue by RessCris2** [alibaba/graph-learn#177]
When I try to import  tf using

import graphlearn.python.nn.tf as tfg

I got error:
ImportError: cannot import name 'pywrap_graphlearn' from 'graphlearn' (unknown location)
How to deal with it?

**Comment by RessCris2** [comment]
ok , after re pip install and restart kernel, fixed!

**Comment by RessCris2** [comment]
ok , after re pip install and restart kernel, fixed!

**Comment by banbsyip** [comment]
> import graphlearn.python.nn.tf as tfg

what means of 'after re pip install and restart kernel'? the kernel is ?
