### ISSUE TITLE
graphsage训练问题

### ISSUE THREAD

**Issue by banbsyip** [alibaba/graph-learn#180]
如果一个图节点只有一度邻居，那这个节点可以进行graphsage训练吗？

**Comment by baoleai** [comment]
Yes, you can. The graphsage example we provide supports 1-hop neighbors aggregation.

**Comment by banbsyip** [comment]
> Yes, you can. The graphsage example we provide supports 1-hop neighbors aggregation.

我的数据有大量孤立节点和只有一个邻居的节点，我把k设置为2，那么graphsage怎么对这些节点进行k=1的邻居（针对于孤立节点）或者k=2的邻居（针对于只有k=1邻居的节点）进行聚合？我不清楚sage是如何处理的，可以解释下吗？

**Comment by baoleai** [comment]
孤立节点无法进行聚合处理，需要过滤掉。
"只有一个邻居的节点”的情况：
如果使用 https://github.com/alibaba/graph-learn/tree/master/examples/tf/ego_sage ，采样结果以dense的EgoGraph组织，采样时会做默认值填充补齐，比如你采样10个，但只有1个邻居，那么会补齐到10个，补齐方式可以通过 `gl.set_padding_mode`设置，同时GNN也只能是1层。
如果使用 https://github.com/alibaba/graph-learn/tree/master/examples/tf/sage ，采样结果以sparse的SubGraph格式组织，有多少个就采样多少个，GNN层数和采样跳数无关。
关于EgoGraph和SubGraph参考 https://graph-learn.readthedocs.io/zh_CN/latest/algo/gnn_programming_model.html

**Comment by banbsyip** [comment]
> 孤立节点无法进行聚合处理，需要过滤掉。 "只有一个邻居的节点”的情况： 如果使用 https://github.com/alibaba/graph-learn/tree/master/examples/tf/ego_sage ，采样结果以dense的EgoGraph组织，采样时会做默认值填充补齐，比如你采样10个，但只有1个邻居，那么会补齐到10个，补齐方式可以通过 `gl.set_padding_mode`设置，同时GNN也只能是1层。 如果使用 https://github.com/alibaba/graph-learn/tree/master/examples/tf/sage ，采样结果以sparse的SubGraph格式组织，有多少个就采样多少个，GNN层数和采样跳数无关。 关于EgoGraph和SubGraph参考 https://graph-learn.readthedocs.io/zh_CN/latest/algo/gnn_programming_model.html

感谢您的回复，我的理解就是说如果非要设置k=2，那我用EgoGraph的话就必须要剔除那些只有一度邻居节点的节点，而SubGraph的话，不用设置k等于几，会把节点的所有跳数的邻居都采样。是这样吧？

**Comment by banbsyip** [comment]
> 孤立节点无法进行聚合处理，需要过滤掉。 "只有一个邻居的节点”的情况： 如果使用 https://github.com/alibaba/graph-learn/tree/master/examples/tf/ego_sage ，采样结果以dense的EgoGraph组织，采样时会做默认值填充补齐，比如你采样10个，但只有1个邻居，那么会补齐到10个，补齐方式可以通过 `gl.set_padding_mode`设置，同时GNN也只能是1层。 如果使用 https://github.com/alibaba/graph-learn/tree/master/examples/tf/sage ，采样结果以sparse的SubGraph格式组织，有多少个就采样多少个，GNN层数和采样跳数无关。 关于EgoGraph和SubGraph参考 https://graph-learn.readthedocs.io/zh_CN/latest/algo/gnn_programming_model.html

![image](https://user-images.githubusercontent.com/18277076/156340743-254ebdee-5292-48a7-b1c6-812ae94fcc21.png)

我这做了个对比实验用我自己的数据，数据有很多只有一跳邻居的节点
设置hops_num=2，训练结果
val Accuracy is: 0.9440
test ...
test Accuracy is: 0.9516
设置hops_num=1，训练结果
val Accuracy is: 0.9860
test ...
test Accuracy is: 0.9850
效果差了不少，这个是不是因为很多节点没有2跳的邻居，导致在二跳向一跳embading的时候会产生大量空值造成的？

**Comment by baoleai** [comment]
在graphsage例子里，边的decoder里directed=False，也就是按照无向图来处理，所以只要存在邻居，2跳都能采样到。
可以把邻居默认填充方式(默认为填充固定值0)，改成循环填充邻居 `gl.set_padding_mode(1)` 试试（加在g.init()前）。
也可能是在src节点只有1跳的图上，2跳采样时，又采样到了src自己，这样二跳聚合可能没有太大意义。

**Comment by banbsyip** [comment]
> 在graphsage例子里，边的decoder里directed=False，也就是按照无向图来处理，所以只要存在邻居，2跳都能采样到。 可以把邻居默认填充方式(默认为填充固定值0)，改成循环填充邻居 `gl.set_padding_mode(1)` 试试（加在g.init()前）。 也可能是在src节点只有1跳的图上，2跳采样时，又采样到了src自己，这样二跳聚合可能没有太大意义。

> 我试试，因为我在用graphscope，我看这个是在graphlearn基础上做的，我看下源代码再根据您的思路修改一下，谢谢

> 在graphsage例子里，边的decoder里directed=False，也就是按照无向图来处理，所以只要存在邻居，2跳都能采样到。 可以把邻居默认填充方式(默认为填充固定值0)，改成循环填充邻居 `gl.set_padding_mode(1)` 试试（加在g.init()前）。 也可能是在src节点只有1跳的图上，2跳采样时，又采样到了src自己，这样二跳聚合可能没有太大意义。

 我试试，因为我在用graphscope，我看这个是在graphlearn基础上做的，我看下源代码再根据您的思路修改一下，感谢
