### ISSUE TITLE
pip安装后运行报错

### ISSUE THREAD

**Issue by bookug** [alibaba/graph-learn#183]
首先，pip3 install graphlearn后成功安装（这里官方文档有误，不是graph-learn）
但安装后运行demo，会报找不到graphlearn.python错误。
github代码仓里graphlearn/python/nn是有的，但是安装后的site-packages/graphlearn/里却没有。。。

**Comment by baoleai** [comment]
Hi, since `graphlearn` is already registered in pypi, so we use name `graph-learn`, please try `pip3 install graph-learn` and make sure you install the correct package.

**Comment by bookug** [comment]
graph-learn  can not be found...

**Comment by bookug** [comment]
https://pypi.org/project/graph-learn/

**Comment by bookug** [comment]
> https://pypi.org/project/graph-learn/

I found the whl files in https://pypi.org/project/graph-learn/#files
but the versionnot matched, it seems that the whl is built on Linux kernel 2.24? that is too old.

**Comment by Seventeen17** [comment]
2.24 is the lowest required version of glibc, not linux kernel version.  We built the whl based on manylinux2.24. 
Please check your glibc version by `ldd --version`.

Also, you can also build from source based on your environment.
