### ISSUE TITLE
训练时目前只用到一个cpu核？不能配置多核训练？

### ISSUE THREAD

**Issue by zhixiongning** [alibaba/graph-learn#185]
在训练时发现cpu占有率只有130%，目前是不支持多核训练么？

**Comment by baoleai** [comment]
Both Graph-Learn's sampling and training are supported for multiple cores, how did you configure it? Which example did you run?

**Comment by zhixiongning** [comment]
> Both Graph-Learn's sampling and training are supported for multiple cores, how did you configure it? Which example did you run?

我使用的是examples/tf/gcn/train_supervised.py这个例子，但把数据集换成了ogbn-products。我没有部署k8s，单机测试的，graph.init用的默认值，导图时CPU占用率有1000%以上，但training时就只有130%了。

**Comment by baoleai** [comment]
It looks like you're using version 0.4.0. Sampling has been optimized in our latest version [1.0.1](https://github.com/alibaba/graph-learn/releases/tag/v1.0.1), so we recommend you try https://github.com/alibaba/graph-learn/tree/master/examples/tf/sage with the latest version
