### ISSUE TITLE
关于分布式下的邻居采样问题

### ISSUE THREAD

**Issue by yeshenyong** [alibaba/graph-learn#188]
论文提及了：**如果一个顶点的邻居没有被缓存，则需要调用远程Graph Server**，请问现在的系统实现了这个功能吗？（代码上貌似只有对DefaultNeighborId进行FillWith 处理）。如果没有实现的话，是否可以理解采样局限于本地。

**Comment by baoleai** [comment]
Yes, GL supports remote sampling by RPC. 
Doc: https://graph-learn.readthedocs.io/en/latest/operator.html#distributed-runtime-design 
Code:  https://github.com/alibaba/graph-learn/blob/master/graphlearn/core/operator/sampler/sampler.h#L53
