### ISSUE TITLE
Client talks to multiple servers or single server?

### ISSUE THREAD

**Issue by cozilla** [alibaba/graph-learn#19]
In [Distribute runtime design](https://github.com/alibaba/graph-learn/blob/master/docs/operator.md#distribute-runtime-design), it shows client will send op request to **only 1 server**, and server will send partitioned requests.
However, [Distributed mode](https://github.com/alibaba/graph-learn/blob/master/docs/distribution.md) shows client will connect with **multiple servers**.
I'm a bit confused about client-server mode. **does client send op request to multiple servers?**
 I checked [grpc_client.cc](https://github.com/alibaba/graph-learn/blob/master/graphlearn/service/dist/grpc_client.cc#L36). It seems client will connect to 1 server. if so, [this picture](https://github.com/alibaba/graph-learn/blob/master/docs/distribution.md) is not correct.

**Comment by jackonan** [comment]
Usually, the count of clients is much more than the count of servers.  A client may work well by connecting to ONE server in most of the time. In the above cases, we assume that all the environments, such as data loading balance, network connection, and server recovery from failure, are all in a ideal state. Unfortunately it is not, especially in industry cases. We need to apply more than one options for each client. If so, please modify the REPLICA number of balancer which is called in ChannelManager, or implement a new LoadBalancer sub-class based on your needs.

**Comment by cozilla** [comment]
I definitely agree that service recovery is quite important for high availability services. 
Let me ask question in different way: If all servers are healthy, for each Op request, client only send op request to 1 server. Is it correct?

**Comment by jackonan** [comment]
correct
