### ISSUE TITLE
[consult] dynamic graph storage 

### ISSUE THREAD

**Issue by littleDrew** [alibaba/graph-learn#192]
- here i want to consult graph storage, here using `id_indexing`, which help using std::vector to store the corrsponding data
- here am thinking, in **dynamic graph**, if there are node and edge add/delete, how should the vector **memory been 
collect**(reclamation), other wise the deleted part may never been used again.
- i am curious about **how will graph-learn support dynamic graph as for graph store part** : )

> https://github.com/alibaba/graph-learn/blob/master/graphlearn/core/graph/storage/memory_adj_matrix.cc#L74

**Comment by baoleai** [comment]
Yes, the current version does not support efficient storage of dynamic graphs. We will release dynamic graph service in a few weeks.

**Comment by baoleai** [comment]
see #196
