### ISSUE TITLE
gcn 报错

### ISSUE THREAD

**Issue by tianrking** [alibaba/graph-learn#194]
world_size: 1 rank: 0
Traceback (most recent call last):
  File "train.py", line 228, in <module>
    run(args)
  File "train.py", line 151, in run
    g.init(task_index=args.rank, hosts=thg.get_cluster_spec())
AttributeError: module 'graphlearn.python.nn.pytorch' has no attribute 'get_cluster_spec'

**Comment by baoleai** [comment]
Hi, it seems that you use v1.0.1 pip wheel but run example at master branch.
We will release v1.1.0(check out from master) asap. For now, you can just checkout branch v1.0.1 or add https://github.com/alibaba/graph-learn/blob/master/graphlearn/python/nn/pytorch/__init__.py#L17 into your corresponding installed package file.
