### ISSUE TITLE
GL编译问题

### ISSUE THREAD

**Issue by UVUUUVUU** [alibaba/graph-learn#198]
请问项目结构在前几天的修改后第三方依赖文件夹下已经没有了protobuf库，会导致编译错误，这个是要怎么解决呢？

**Comment by baoleai** [comment]
@goldenleaves

**Comment by baoleai** [comment]
Actually, grpc module contains protobuf module，so on master branch when you compile the grpc library it will automatically compile protobuf. Please make sure that all third party libraries are downloaded in full. You can run `git submodule update --recursive` to download the whole submodules.
cc @goldenleaves

**Comment by baoleai** [comment]
The new compile command is as follows，
```
cd graphlearn/
./install_dependencies.sh
mkdir build
cd build
cmake -DDEBUG=ON -DGL_PYTHON_BIN=python ..
make -j
make python -j
```

**Comment by UVUUUVUU** [comment]
ok, i got it, thanks a lot.
