### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [alibaba/graph-learn#2]
Would you like to [wrap any pointer data members](https://github.com/alibaba/graph-learn/blob/e7316a697e8b24812ab875c591c0085fb63ecf69/graphlearn/platform/local/local_file_system.cc#L78 "Update candidate: LocalStructuredAccessFile class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by jackonan** [comment]
Raw pointer is a frugal way if you can control its lifecycle.

**Comment by elfring** [comment]
I suggest to [achieve safe resource management](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "C++ core guideline “R.11: Avoid calling new and delete explicitly”").
