### ISSUE TITLE
GL graph partition question

### ISSUE THREAD

**Issue by UVUUUVUU** [alibaba/graph-learn#201]
想问一下，源码中做graph partition的代码是在什么位置呢，在graphlearn/src/core/partition下好像没有看到论文里提到的四种内置的图分割算法呀。

**Comment by baoleai** [comment]
Currently there are indeed only two partition strategies, we will later extend the partition algorithm

**Comment by UVUUUVUU** [comment]
两个分区策略是定义在partition下的no_partitioner.h和hash_partitioner.h吗？

**Comment by UVUUUVUU** [comment]
我观察到在hash_partition.h头文件下的HasPartitionKey()、PartitionId()等接口并未找到，这是怎么回事呢

**Comment by baoleai** [comment]
There are methods of `OpRequest`, see https://github.com/alibaba/graph-learn/blob/master/graphlearn/src/service/request/op_request.cc#L37.
