### ISSUE TITLE
graph partition question

### ISSUE THREAD

**Issue by UVUUUVUU** [alibaba/graph-learn#206]
用户文档上写了：
分布式场景下，即存在多个GraphLearn Server时，构图时会自动进行图的partition, 将图分布式存储。默认partition是按照src_id % server数进行节点和边的分配。
想问一下这个partition方法是在源码的什么位置呢，我在源码中没有找到。我目前是想重写自己的partition策略并加进去，期待回答谢谢。

**Comment by baoleai** [comment]
https://github.com/alibaba/graph-learn/blob/master/graphlearn/src/core/partition/hash_partitioner.h
