### ISSUE TITLE
gsl_client的包中没有org.aliyun.dgs的jar包，导致无法运行

### ISSUE THREAD

**Issue by lvf0052** [alibaba/graph-learn#219]
![image](https://user-images.githubusercontent.com/18576873/187426854-b82af7b0-a53e-49d3-a21e-e5cd020750c4.png)

**Comment by lvf0052** [comment]
已找到包，需使用flatc使用fbs生成java文件。

**Comment by Seventeen17** [comment]
Thanks for your feedback on the DGS. Java fbs code generation is in the pom and `gen_fbs.sh` will be automatically called when compile with `mvn`.
