### ISSUE TITLE
关于gsl_client的test包org.aliyun.PredictClientTest的问题

### ISSUE THREAD

**Issue by lvf0052** [alibaba/graph-learn#220]
先贴代码：
```
public class PredictClientTest extends TestCase {
  private ArrayList<Integer> vtypes = new ArrayList<Integer>(Arrays.asList(0, 1, 1));
  private ArrayList<Integer> vops = new ArrayList<Integer>(Arrays.asList(2, 4, 4));
  private ArrayList<Integer> hops = new ArrayList<Integer>(Arrays.asList(1, 10, 5));
  private ArrayList<Integer> eops = new ArrayList<Integer>(Arrays.asList(0, 1, 3));
  private Schema schema;

  public static Test suite() {
    return new TestSuite(PredictClientTest.class);
  }

  private Value generatedValue(int dim) throws UserException {
    long inputVid = 0L;
    Plan plan = new Plan();
    Query query = new Query(plan);
    ValueBuilder builder = new ValueBuilder(query, 1 + 1 + 10 + 10 + 50, schema, 0L, dim);
    builder.addVopRes(2, (short)0, inputVid, 1);
    builder.addEopRes(1, (short)2, (short)0, (short)1, inputVid, 10);
    for (int i = 0; i < 10; ++i) {
      builder.addVopRes(4, (short)1, inputVid + i, 1);
    }
    for (int i = 0; i < 10; ++i) {
      builder.addEopRes(3, (short)3, (short)1, (short)1, inputVid + i, 5);
    }
    for (int i = 0; i < 10 * 5; ++i) {
      builder.addVopRes(4, (short)1, inputVid + i, 1);
    }
    Value val = builder.finish();
    return val;
  }

  public void testPredict() throws UserException, IOException{
    schema = Schema.parseFrom("../conf/u2i/schema.u2i.json");
    int dim = 10;
    TFPredictClient client = new TFPredictClient(schema, "localhost", 9000);
    Value content = generatedValue(dim);
    EgoGraph egoGraph = content.getEgoGraph(vtypes, vops, hops, eops);
    ArrayList<Integer> phs = new ArrayList<Integer>(Arrays.asList(0, 3, 4));
    client.predict("egomodel", 1, egoGraph, phs);
  }
}

```
对于这个测试类我有以下几点疑问：
1. 这个类是用来进行模型预测的测试类吗？
2. vtypes是否代表【节点】的类型，vops代表【节点】的标识，eops代表【边】的标识，那hops代表什么？
3. 为什么需要执行generatedValue(dim)这个代码，然后用生成的数据+上vtypes、vops、eops、hops，来构造EgoGraph这个对象
4. phs全程是placeholders把，这个指的是我们待预测的数据吗？
5. 对应第一点，如果这个是一个模型预测的测试类，参数中我们为什么需要传入egograph对象。
对以上5个点，是我在看官方GraphLearn文档中后依旧没解答的疑惑，希望能够得到指点，解惑一下，谢谢。

**Comment by Seventeen17** [comment]
1. 这个类是用来进行UT的，使用动态图采样服务进行模型预测包含：
（1）向动态图采样服务发起Query，获得样本；
（2）使用样本向TF model service发起预测请求，获取预测结果。
这里为了单独测试第（2）部分的正确性，直接在本地构造了样本，问题2中的几个参数也是构造样本时使用的，hops是指每一个采样hop的nbr count；
2. 如上
3. 如上
4. 这里phs是指服务的模型的输入。因为训练侧训练得到的模型可能是一个二部图模型，只用其中一部分进行模型服务。这时候我们需要根据tensorboard分析，抽取出来这个单侧模型的输入是哪几个placeholders
5. 同1
完整的测试是App.java

**Comment by lvf0052** [comment]
@Seventeen17 
谢谢你的解答，有你的解答，我就明白一些了。
也就是说【手动】编写的样本等于g.V("user").feed(source)...(后续还有一堆的代码)，然后用这个样本进行预测。
我说一下我的理解，举以下的例子：
场景说明：图结构是(顾客)-[购买]->(书籍)
1. 我训练了一个模型，用于预测，某某顾客可能会买什么书籍。
2. 然后现在来了一个新的顾客，将这个顾客(g.V(user))在【动态图】中获取一个样本，构造成EgoGraph
3. 然后再将这个样本传进模型里面进行计算，得到的结果就是，这个(顾客)-可能购买->(书籍)
===
不知道我的理解是否正确。
还是十分感谢你的解答，谢谢。

**Comment by Seventeen17** [comment]
是的，您理解的没问题。
其中第3点我再加以说明：
在您举例的这个场景中，顾客的表征可能会随着图结构、顾客原始特征的变化而动态变化，但是书籍的表征很可能是静态的。
因此，在线推理中，我们只用顾客侧的EgoGraph，计算顾客实时表征，然后和静态书籍表征进行相似度的计算，推断购买的可能性。

**Comment by lvf0052** [comment]
嗯嗯，谢谢您的解答。
