### ISSUE TITLE
新版代码中删除了旧版的example

### ISSUE THREAD

**Issue by 4613** [alibaba/graph-learn#222]
旧版example在顶层目录，目录中有transe,deepwalk等样例，目前master中此块样例删除；
删除的原因是在增加dgs后，无法运行吗？
这块样例后面会完善吗？

**Comment by Seventeen17** [comment]
我们近期开源了DGS代码，因此整体目录结构进行了调整，原先graphlearn的样例放在graph-learn/graphlearn/examples/tf中，
最新版本examples中包含GNN类模型SAGE等。

在早前推出GSL接口和采样加速引擎时，我们对GNN类模型进行了采样优化，transe,deepwalk等GE类模型未做采样优化，需要用GE类模型，建议使用0.4版本
