### ISSUE TITLE
在线推理服务等新特性什么时候推出？

### ISSUE THREAD

**Issue by 4613** [alibaba/graph-learn#223]
![image](https://user-images.githubusercontent.com/5295924/187825013-c006e9c4-9e86-4f8f-9de7-5640600f0355.png)
在使用过程发现目前在推理的相关API和实现比较少，相关推理结果也大多是tensor或嵌入，对于应用端的使用不是很友好。
在相关会议和宣传材料中，有写在线推理服务会在之后开源，请问目前有具体计划吗？

**Comment by Seventeen17** [comment]
您好，在线推理服务已经开源，https://graph-learn.readthedocs.io/zh_CN/latest/zh_CN/dgs/intro.html
