### ISSUE TITLE
Current Version whether support Caching Neighbors of Important Vertices

### ISSUE THREAD

**Issue by YijianLiu** [alibaba/graph-learn#237]
Hello, 1 year ago I see it doesn't support of caching neighbors. Whether current version support this function, if not, what are the main difficulties? Urgently need your answer, thanks a lot!

**Comment by Seventeen17** [comment]
We implement **batch cache** in this version, by prefetching neighbors and features for several batches and caching them in a [TapeStore](https://github.com/alibaba/graph-learn/blob/master/graphlearn/src/core/dag/tape.h); For computation, the sampling and feature extraction operators are organized as DAG, and the computation is executed in parallel inter- and intra- DAGs, which substantially improves the sampling performance.
The batch cache achieves the desired performance in most of our sampling scenarios. If the capacity of the cache is sufficient and sampling is still a performance bottleneck situation, adding hotspot cache can also orthogonally improve the sampling performance.

Translated with www.DeepL.com/Translator (free version), and computing the performance operators of events and attribute extraction through DAG organization, parallel execution within Dag and between Dags, improving large capacity .
Increasing the hotspot cache can also improve performance if the cache capacity is underperforming at the same time. Batch caching has achieved ideal performance in several of our scenarios, so add caching for now.

**Comment by Seventeen17** [comment]
We implement batch cache in this version, by prefetching neighbors and features for several batches and caching them in a [TapeStore](https://github.com/alibaba/graph-learn/blob/master/graphlearn/src/core/dag/tape.h); For computation, the sampling and feature extraction operators are organized as DAG, and the computation is executed in parallel inter- and intra- DAGs, which substantially improves the sampling performance.

The batch cache achieves the desired performance in most of our sampling scenarios. If the capacity of the cache is sufficient and sampling is still a performance bottleneck situation, adding hotspot cache can also orthogonally improve the sampling performance.

**Comment by YijianLiu** [comment]
> We implement batch cache in this version, by prefetching neighbors and features for several batches and caching them in a [TapeStore](https://github.com/alibaba/graph-learn/blob/master/graphlearn/src/core/dag/tape.h); For computation, the sampling and feature extraction operators are organized as DAG, and the computation is executed in parallel inter- and intra- DAGs, which substantially improves the sampling performance.
> 
> The batch cache achieves the desired performance in most of our sampling scenarios. If the capacity of the cache is sufficient and sampling is still a performance bottleneck situation, adding hotspot cache can also orthogonally improve the sampling performance.

According to my understanding, it means that sampling and training are in parallel?  When the first batch is training, it begins to prefetch next batch of neighbors and features?

**Comment by Seventeen17** [comment]
Yeah

**Comment by YijianLiu** [comment]
> Yeah

Hello, I have a question that why not use pytorch DataLoader workers or tensorflow  tf.data.Dataset.prefetch,
I think both of them can also achieve prefetch for batches, and why you achieve again by c++

**Comment by LiSu** [comment]
As graphlearn only uses Pytorch for training, it needs its own dataloader to transform the sampling results into the formats that the trainer requires.
