### ISSUE TITLE
执行tutorial的时候k8s中有些pod启动失败

### ISSUE THREAD

**Issue by Homura2333** [alibaba/graph-learn#242]
执行到这一步：
![](https://user-images.githubusercontent.com/39360166/205922743-0f30ebcc-1d3b-48d1-b630-e203bfbdc9ee.png)

完成之后查看k8s的pods，发现有两个pods的STATUS显示running，但是READY一直都是0/1。
<img width="625" alt="image" src="https://user-images.githubusercontent.com/39360166/206205684-6b2181cc-60f3-4f50-b235-d9b1b7217605.png">

执行`kubectl describe pod`之后，返回以下信息：
 
<img width="877" alt="EA012B69-4ACF-48DC-9AD5-775B37B0360E" src="https://user-images.githubusercontent.com/39360166/206206387-062800b3-057f-4fb9-b67b-73c76baa06c0.png">
<img width="809" alt="image" src="https://user-images.githubusercontent.com/39360166/206206603-dd98551a-c360-4885-807e-8f972b054b64.png">

提示探针连接失败了，我在执行`curl 10.244.46.4:10000`之后也确实无法连接，但是看样子ip和端口应该是正确的。

这可能会是什么问题呢？相关的配置文件我都没有修改过，是直接按照tutorial的指引跑的。

**Comment by Homura2333** [comment]
顺便一提，执行
```
export DgsServiceIP=$(kubectl get ingress --namespace default dgs-u2i-frontend-ingress --output jsonpath='{.status.loadBalancer.ingress[0].ip}')
echo $DgsServiceIP
```
也无法输出service ip，是空的。
执行`kubectl get ingress dgs-u2i-frontend-ingress`之后返回如下：
<img width="651" alt="image" src="https://user-images.githubusercontent.com/39360166/206208757-f030597b-b63b-472d-acdf-f80e8031b3c4.png">
ADDRESS字段是空的。这又是为什么呢？是否跟我没有正确配置好nginx controller有关系呢？
执行` kubectl get svc`返回如下：
<img width="713" alt="image" src="https://user-images.githubusercontent.com/39360166/206209164-60a7b962-d62b-4ec0-89d5-948758fb42a4.png">
有没有人能帮助我？

**Comment by goldenleaves** [comment]
能否给出serving worker里面更详细的日志嘛，目前看来你给出的log只显示了serving worker想coordinator注册了，但是没有显示自己处于ready状态。只有当serving worker处于ready之后，相关的service port才可以被访问。 @Homura2333

**Comment by Homura2333** [comment]
> 能否给出serving worker里面更详细的日志，目前看来你给出的log只显示了serving worker向coordinator注册了，但是没有显示自己处于ready状态。只有当serving worker处于ready之后，相关的service port才可以被访问。 @Homura2333

更详细的log也只能看到这些：
<img width="743" alt="image" src="https://user-images.githubusercontent.com/39360166/206357616-b57304fb-f583-4958-b4b9-396afbe560ed.png">
还有什么其他方法能看到更有用的log吗？

**Comment by Homura2333** [comment]
进入容器内部，/serving_workdir/package/bin下的log如下：
<img width="713" alt="image" src="https://user-images.githubusercontent.com/39360166/206359522-76f35353-8a54-4353-b52f-755cc3bc4b09.png">

**Comment by Homura2333** [comment]
> @Homura2333 看起来是serving worker只是向coordinator注册了，但是没有拿到init info，因此根本没有启动，能够把coordinator的日志也贴一下嘛

<img width="641" alt="image" src="https://user-images.githubusercontent.com/39360166/207303711-f840c5db-9de3-4b05-89c0-376a947e03be.png">

**Comment by goldenleaves** [comment]
@Homura2333 从coordinator的日志来看serving worker的启动流程是正常的，但是init之后的信息并没有出现，说明serving worker在init阶段卡住或者出现了错误，建议检查一下是不是设置的port或者k8s存储出现冲突之类的原因，然后删掉这个release重新拉起试一试。

**Comment by KaisennHu** [comment]
**也是在搭建DGS时，执行完以下命令后，DGS相关pod都error。**
执行命令如下：
`helm install dgs-u2i DGS/dgs
    --set frontend.ingressHostName="dynamic-graph-service.info"
    --set-file graphSchema=./conf/u2i/schema.u2i.json
    --set kafka.dl2spl.servers=[localhost:9092]
    --set kafka.dl2spl.topic="record-batches"
    --set kafka.dl2spl.partitions=4
    --set kafka.spl2srv.servers=[localhost:9092]
    --set kafka.spl2srv.topic="sample-batches"
    --set kafka.spl2srv.partitions=4
    --set glog.toConsole=true`
pod状态如下：
![image](https://user-images.githubusercontent.com/74917084/222075414-c6d694f2-0c6f-40f0-bd5d-06d1f6199be0.png)
pod的log显示，并没有对应的目录，例如/coordinator_workdir、/serving_workdir、/sampling_workdir等：
![image](https://user-images.githubusercontent.com/74917084/222076069-6ec28cf0-7945-4d23-bb74-d67e62922673.png)
**想请问这个问题应该如何解决？是否是因为容器镜像有问题？**
