### ISSUE TITLE
GraphLearn动态图在线推理仅支持TopK采样吗？

### ISSUE THREAD

**Issue by frapuccino** [alibaba/graph-learn#250]
GraphLearn动态图在线推理时，只能采用Topk采样吗？如果是这样，具体在线推理时图数据必须要保证带边权吗（按边权求TopK）？

**Comment by Seventeen17** [comment]
DGS currently supports tok-timestamp sampling, so edge should be with timestamp, but not need to be weighted.

**Comment by frapuccino** [comment]
明白，谢谢～还有就是这里的时间戳是流入图存储的当前时间戳，还是业务中打的时间戳呀？举个例子，在一些交互的场景，确实可以提取到时间戳(交互时发生的时间)，但是针对好友关系等信息，这个是没有时间戳的，GraphLearn是否能处理到好友关系这种场景呢？

**Comment by frapuccino** [comment]
> DGS currently supports tok-timestamp sampling, so edge should be with timestamp, but not need to be weighted.

**Comment by LiSu** [comment]
DGS只假设流入系统的图更新都包含一个时间戳，时间戳的语意是用户自定义的，不是按照流入系统的时间。
