### ISSUE TITLE
Synchronous Training

### ISSUE THREAD

**Issue by power1628** [alibaba/graph-learn#3]
Great work!
I wonder how graph-learn do synchronous training.
It would be great if there's a distributed synchronous training example.

**Comment by baoleai** [comment]
We use GraphSAGE as an example to show how to train in parallel on multiple machines. Currently we just provides asynchronous training example, you can simply replace it with synchronous training by using synchronous optimizer in TensorFlow.

**Comment by archwalker** [comment]
Initialize optimizer with `use_locking=True` flag in [DistTFTrainer](https://github.com/alibaba/graph-learn/blob/060ef65db0cf7dc48191424455323ae477018b06/graphlearn/python/model/tf/trainer.py#L199) will perform synchronous training in distributed settings.

**Comment by power1628** [comment]
> Initialize optimizer with `use_locking=True` flag in [DistTFTrainer](https://github.com/alibaba/graph-learn/blob/060ef65db0cf7dc48191424455323ae477018b06/graphlearn/python/model/tf/trainer.py#L199) will perform synchronous training in distributed settings. Modify code [here](https://github.com/alibaba/graph-learn/blob/060ef65db0cf7dc48191424455323ae477018b06/examples/tf/graphsage/dist_train.py#L87)

Are you sure?

**Comment by archwalker** [comment]
> > Initialize optimizer with `use_locking=True` flag in [DistTFTrainer](https://github.com/alibaba/graph-learn/blob/060ef65db0cf7dc48191424455323ae477018b06/graphlearn/python/model/tf/trainer.py#L199) will perform synchronous training in distributed settings. Modify code [here](https://github.com/alibaba/graph-learn/blob/060ef65db0cf7dc48191424455323ae477018b06/examples/tf/graphsage/dist_train.py#L87)
> 
> Are you sure?
> The `use_locking` only guarantees multi-thread safety, not distributed synchronous training.
> BTW, I don't think this issue should be closed.

I misunderstood you. Basically, to use distributed synchronous training, one needs to:
1. Wrap optimizer with tf.train.SyncReplicasOptimizer [here](https://github.com/alibaba/graph-learn/blob/060ef65db0cf7dc48191424455323ae477018b06/examples/tf/graphsage/dist_train.py#L87)
2. Add a synchronous hook in MonitoredTrainSession [here](https://github.com/alibaba/graph-learn/blob/1c48ccb5afb15d484453039ddfac8791557d2c22/graphlearn/python/model/tf/trainer.py#L219)

A synchronous example will be posted soon.

**Comment by power1628** [comment]
This issue should be re-opened since it's not fixed.

**Comment by baoleai** [comment]
The question is how to synchronize training using TensorFLow, the above discussion has given advice.
