### ISSUE TITLE
您好，请问Graph-Learn支持python3吗？

### ISSUE THREAD

**Issue by wangzipengnv** [alibaba/graph-learn#32]
我看有一句话：Otherwise, please refer to the section 'build from source'. 但是一直没法安装成功~ 我这边的环境是python3; 阿里金融云的centos系统。但是运行以下这段话一直不行，我从网页下载master包复制过去之后，git和make操作还是不行。
git clone https://github.com/alibaba/graph-learn.git
cd graph-learn
git submodule update --init
make test
make python

**Comment by archwalker** [comment]
Please use python2 for now, see #9
