### ISSUE TITLE
Standard Recommender Dataset on Bipartite GraphSage

### ISSUE THREAD

**Issue by RomFas** [alibaba/graph-learn#34]
Hi! First of all, thanks for releasing graph-learn!

Regarding the bipartite version of GraphSage, I am aware that you use the `u2i.zip` dataset, I have successfully run the model on that dummy dataset without issues. 

I do believe though that the `u2i` dataset does not include any distinct node features whatsoever, much less feature vectors of different length (depending on the node type, e.g. users or items). 

Have you tested the model on a standard recommendation dataset, like `MovieLens`? If yes, does it work out-of-the-box? I haven't really got to try it out on the dataset myself, just checking if indeed the model supports fully fledged node features, especially of different lengths.

Thanks in advance!

**Comment by baoleai** [comment]
The `u2i` data is only used as a simple example. We do have plans to test on public data sets. Node features of different lengths are supported because graph-learn supports string attributes.
