### ISSUE TITLE
how to train with hdfs source data, and how to save embedding

### ISSUE THREAD

**Issue by joseph-chan** [alibaba/graph-learn#35]
I don't see any demo about gcn or graph algorithm trained with hdfs data, and pull the node embedding to local or hdfs for use. would you add some, thank you!

**Comment by jackonan** [comment]
HDFS is not supported in this version. For training in distributed mode, we mount NFS to local. To support other distributed file systems, we abstract FileSystem interface [here](https://github.com/alibaba/graph-learn/blob/master/graphlearn/platform/file_system.h).  You can add HDFS implementation if needed.

**Comment by baoleai** [comment]
Already supports reading data from hdfs.
