### ISSUE TITLE
ResourceExhaustedError in distributed mode

### ISSUE THREAD

**Issue by hansugu** [alibaba/graph-learn#36]
If I change neighs_num to [25,10], and batch_size to 100 in this file:
https://github.com/alibaba/graph-learn/blob/master/examples/tf/graphsage/dist_train.py

I see the ResourceExhaustedError and it seems related to the graph engine operations. I am not seeing any CPU, RAM bottleneck. 

I run 2 parameter servers and 2 workers as shown in the wiki.

The error is: 

23:56:40.288581 61070 notification.cc:194] RpcNotification:Failed	req_type:LookupNodes	status:Resource exhausted:Received message larger than max (8066392 vs. 4194304)
23:56:40.322116 61070 distribute_runner.h:125] Rpc failed:Resource exhausted:Received message larger than max (8066392 vs. 4194304)name:LookupNodes

Any idea how to fix this?

**Comment by hansugu** [comment]
It seems relevant to the maximum message size in GRPC is 4MB. 
https://jbrandhorst.com/post/grpc-binary-blob-stream/

Hope someone can help fix this as the current distributed mode is practically unusable.

**Comment by baoleai** [comment]
You can add `gl.set_rpc_message_max_size(xxx)` (https://github.com/alibaba/graph-learn/blob/master/graphlearn/python/config.py#L71) before `g.init` to set GRPC max msg size.

**Comment by hansugu** [comment]
I did this. Does not seem to take any effect. Moved gl.set_rpc_message_max_size(10000000) to the beginning of the file does not help either. The msg size is still 4MB as default.

  g = load_graph(config)
  g_role = "server"
  if FLAGS.job_name == "worker":
    g_role = "client"
  gl.set_rpc_message_max_size(10000000)
  g.init(cluster=graph_cluster, job_name=g_role, task_index=FLAGS.task_index)
  train(config, g)

**Comment by baoleai** [comment]
Does the err log changed? `10000000 / 1024 / 1024` M may still too small.

**Comment by hansugu** [comment]
@baoleai 
No. Error log still shows 4MB. I do not think gl.set_rpc_message_max_size(xxx) is taking effect at all. I think somehow the c++ code is not setting the msg size in GRPC.
