### ISSUE TITLE
graphsage train_unsupervised.py get killed while save embeddings

### ISSUE THREAD

**Issue by kevinyuan** [alibaba/graph-learn#39]
Dear developpers,

When I run the graphsage ppi training exmaple, the script get killed while save embeddings:

> Epoch 00, Iteration 110, Time(s) 2.8076, Loss 1.26855
> Epoch 00, Iteration 111, Time(s) 0.6244, Loss 1.25834
> save embedding...
> (a few minutes later)
> Killed
> 

I confirm the ./id_emb exist on the right path and there're 18G space availabe on the disk.

Could you kindly let me know what's the possible reason and how to fix this issue ?

Thanks very much!

Kevin

**Comment by archwalker** [comment]
Can you please take a look at the memory usage? It is generally caused by memory consumption.

**Comment by kevinyuan** [comment]
The process is occupying 12g memory, and when the embedding is being written, it tried to allocate more memory and the peak system memory utilization is about 95%.


Thanks.

Kevin Yuan


在 2020年4月28日，下午1:10，archwalker <notifications@github.com> 写道：

﻿

Can you please take a look at the memory usage? It is generally caused by memory consumption.

**Comment by archwalker** [comment]
Yes, that relates to the memory problem. We use np.save to save the whole embedding matrix at ones, which would cause a huge memory consumption problem, but this problem does not show up when we test the program on a server. I will fix this problem.

For now, you may:
1. try to save with `pickle`, it might work.
2. separate the embedding matrix and save them one by one.

**Comment by archwalker** [comment]
Hi, while modifying the code to save embeddings partially, we found a memory leak problem also related to your case and solve it #46 , you can try again to see whether it has been fixed.
