### ISSUE TITLE
How to partition the graph in distributed training?

### ISSUE THREAD

**Issue by soodoshll** [alibaba/graph-learn#40]
Hello. I'm interested in how to use METIS partitioning algorithm with GL. Is there any tutorial or doc? Thank you!

**Comment by Seventeen17** [comment]
METIS partitioning algorithm has not been released in GraphLearn. You can follow [hash_partitioner.h](https://github.com/alibaba/graph-learn/blob/master/graphlearn/core/partition/hash_partitioner.h) to implement your own METIS partitioner.

**Comment by Seventeen17** [comment]
Maybe adding a tutorial of extending partitioning algorithms to doc [extend](https://github.com/alibaba/graph-learn/blob/master/docs/extend.md) is better.
What do you think? @jackonan @baoleai .

**Comment by jackonan** [comment]
@Seventeen17 Agree. @soodoshll Just like @Seventeen17 said, you can refer to hash_partitioner.h to extend your partition strategy.
