### ISSUE TITLE
Any plan to sample with node attribute?

### ISSUE THREAD

**Issue by formath** [alibaba/graph-learn#44]
An example
```
g.V("user").with_attribute("gender=man").batch(64).outV("buy").sample(2).with_attribute("city=1").by("random")
```

**Comment by formath** [comment]
@Seventeen17 Your pr is not relevant with this issue. Please change the link.

**Comment by Seventeen17** [comment]
> @Seventeen17 Your pr is not relevant with this issue. Please change the link.

Sorry, I did it wrong, and I have reopened this issue. Let me figure it out with how to change the link.

**Comment by Seventeen17** [comment]
About this issue, we have't support a sample strategy with node attribute , you can implement this sampler following the guide: [doc](https://github.com/alibaba/graph-learn/blob/master/docs/operator.md) if you need it for recently, and welcome to contribution.
