### ISSUE TITLE
[Question] Implementing my own embedding in AliGraph

### ISSUE THREAD

**Issue by spapadias** [alibaba/graph-learn#47]
Hello AliGraph people!

I read the VLDB 2019 paper and I found it very interesting. It is great that the project is open source.

I am wondering if I can implement my own embedding algorithm on top of your system. For example can I implement DeepWalk in AliGraph?

If yes, do you provide abstractions for defining random-walk operations in AliGraph?
If no, is it possible to build such abstractions in your system?

Thanks in advance.

Best,
Makis

**Comment by archwalker** [comment]
Hi spapadias, thanks for your interest. We have defined a gremlin-like API `sample` to provide random-walk operations like this [L75](https://github.com/alibaba/graph-learn/blob/890ed37bb2c14cdcd0e89a03451e90ed558ffb5a/examples/tf/deepwalk/deepwalk.py#L75), the [deepwalk](https://github.com/alibaba/graph-learn/blob/890ed37bb2c14cdcd0e89a03451e90ed558ffb5a/examples/tf/deepwalk/deepwalk.py) example can be a good start to implement your algorithm.
