### ISSUE TITLE
issue in document

### ISSUE THREAD

**Issue by patricxu** [alibaba/graph-learn#50]
https://github.com/alibaba/graph-learn/blob/master/docs/query.md#inneg

inNeg(edge_type). Nodes to Nodes. Traverse to the source negative node along the edge. The edge must be undirected.

For exmaple, the topology is nodeA--(edge)-->nodeB, nodeB.**outNeg**(edge) is nodeA.

SHOULD BE "nodeB.inNeg(edge)" is nodeA？

**Comment by baoleai** [comment]
Yes, it seems to be a typo.
