### ISSUE TITLE
Confusion about your DeepWalk implementation

### ISSUE THREAD

**Issue by TheFinalHydra** [alibaba/graph-learn#51]
Hi, I am exploring your deep-walk  implementation, but I get a little bit confused of the [gen_pair function in _positive_sample](https://github.com/alibaba/graph-learn/blob/master/examples/tf/deepwalk/deepwalk.py#L74) in your implementation.

Specifically, why does the [`gl.gen_pair`](https://github.com/alibaba/graph-learn/blob/d5836069dd886049b8fce5c1d9b2f43a46c51281/graphlearn/python/model/utils/gen_pair.py#L23) slides the windows between paths, not inside each path?

```python
  >>> path = [np.array([1, 2]), np.array([3, 4]), np.array([5, 6])]
  >>> left_window_size = right_window_size = 1
  >>> src_id, dst_ids = gen_pair(path, left_window_size, right_window_size)
  >>> print print(src_ids, dst_ids)
  >>> (array([1, 2, 3, 4, 3, 4, 5, 6]), array([3, 4, 1, 2, 5, 6, 3, 4]))
```

The example about starts from 3 nodes `{1, 3, 5}`, each with a random walk of length 2, which finally collects 3 paths, `p1 : [1, 2], p2 : [3, 4]`, and `p3 : [5, 6]`.

I thought the original DeepWalk paper uses SkipGram on **each of these paths**, so we shall apply SkipGram on p1, p2 and p3 **separately**. But the implementation seems to apply SkipGram on the whole set of paths. For example, it pushes all nodes in the path to pair[0] or pair[1].

Why can we do that instead of the original algorithm in the paper? Or am I misunderstanding anything?

Thanks.

**Comment by TheFinalHydra** [comment]
Never mind, I think I did misunderstand it. I get it now, that each array in the path is the collection node ids in each degree.

**Comment by TheFinalHydra** [comment]
But what if the graph it too sparse that you cannot find a path of length `walk_len`? Will graph-learn pad the path of just discard it?

**Comment by baoleai** [comment]
In fact, for undirected graphs, you can always sample a path of length `walk-len` .

**Comment by TheFinalHydra** [comment]
> In fact, for undirected graphs, you can always sample a path of length `walk-len` .

Yes I get it, thanks for pointing out, but for some directed graphs, how do you solve such potential issue? Is it a good idea to separately apply SkipGram on 2-degree paths, 3-degree paths, etc... or we should avoid using DeepWalk but other algorithms on such sparse directed graph?

**Comment by baoleai** [comment]
I think you can modify the implementation of deepwalk, propose your solution to this situation, welcome to contribute:)
