### ISSUE TITLE
Any plan to decouple TF-PS and distributed graph engine？

### ISSUE THREAD

**Issue by fff-2013** [alibaba/graph-learn#60]
In the current implementation，client and server of graph co-place with TF-worker and TF-parameter-server. 

When I want to use one TF-worker to train and multiple workers to sample data simultaneously(for GPU training). There will be some restrictions under the current architecture. So, any plan to decouple TF-PS and distributed graph engine to make architecture more flexible?

**Comment by jackonan** [comment]
Good suggestion and the solution is coming.
