### ISSUE TITLE
bipartite_graphsage can't train with hops num > 1

### ISSUE THREAD

**Issue by dengfy** [alibaba/graph-learn#66]
I set those config below but  get error info AssertionError: ego_spec num must be the same with hops num!

'hops_num': 3,
'u_neighs_num': [5,3,2],
'i_neighs_num': [5,3,2],

**Comment by baoleai** [comment]
Hi, you need to modify [here](https://github.com/alibaba/graph-learn/blob/master/examples/tf/bipartite_graphsage/bipartite_graph_sage.py#L137) using mulit-hop sampler.

**Comment by baoleai** [comment]
fixed in release v1.0.0.
