### ISSUE TITLE
installation on CentOS 7

### ISSUE THREAD

**Issue by patricxu** [alibaba/graph-learn#7]
I got an error when I try to install from wheel file on CentOS 7. Do you have any plan on CentOS?

`ERROR: graphlearn-0.1-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.
`

**Comment by Seventeen17** [comment]
Ubuntu 16.04 is required for now. For other systems, you can use the docker. We will support wheel packages for different OS and different python versions soon.

**Comment by patricxu** [comment]
I made GL from source on CentOS 7. Here is my notes for the installation:

1. git clone https://github.com/alibaba/graph-learn.git
2. cd graph-learn
3. git submodule update --init
3. make test  
    This step will fail. You have to install gflag (compile as shared library) and glog in advance.
    a) cd to gflag directory 
    b) mkdir build && cd build
    c) cmake -DBUILD_SHARED_LIBS=ON ..
    d) make && make install
    e) at this point you will see libgflag.so in the outputs. [here to the installation of gflag](https://github.com/gflags/gflags/blob/master/INSTALL.md)
    f) cd to glog directory
    h) ./autogen.sh && ./configure && make && make install
4. modity graph-learn/Makefile by adding library path of gflag to test and python
5. export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/libgflag
6. make test
7. make python

**Comment by Seventeen17** [comment]
Thanks for sharing your nodes.

**Comment by jackonan** [comment]
@patricxu did you use `make test -jx`, where x > 1 ？
