### ISSUE TITLE
the result of 'bipartite_graphsage' doesn't turns out to good

### ISSUE THREAD

**Issue by ybeforev** [alibaba/graph-learn#71]
hey guys, thank you for making graph-learn opensourced. however, i have run the demo in bipartite-graphsage, but the result is aweful (with a rather low recall and precision), can you give me some hint on it?

i just follow the instructions on this page: 
[bipartite_graphsage](https://github.com/alibaba/graph-learn/blob/master/examples/tf/bipartite_graphsage/README.md)

**Comment by dengfy** [comment]
yes, i got same problem,.

**Comment by baoleai** [comment]
In fact, the data set is just for showing how to run. Maybe we need a suitable open source data set to test.
