### ISSUE TITLE
Is graph-learn ready for all batch sampling results before training？

### ISSUE THREAD

**Issue by Zdm-Jdsc-lalala** [alibaba/graph-learn#74]
Is graph-learn ready for all batch sampling results before training？
For example, if I set up 1000 training times, the strategy of graph learn is to prepare the data of 1000 batches, and then use the next method to get a batch?
In the distributed mode, I first need to randomly select batch_size IDs as source vertices, 
and then proceed from these source vertices to further sample. 
Are these source vertices selected in the subgraph of each machine or in the whole graph? 
If the sub graph is selected, the communication is reduced, but the effect may be reduced.

Thanks!

**Comment by baoleai** [comment]
Hi, traversal methods like EdgeSampler/NodeSampler only select vertices or edges from local machine，
but when you sample neighbors, GL will query the neighbors of each vertice, and these neighbors may be on other machines.

**Comment by lorinlee** [comment]
@baoleai Is this "Sampling is executed during training" a data pipeline? which means when the first batch is being trained, the next batch is being sampled at the same time?

**Comment by Zdm-Jdsc-lalala** [comment]
> 
> 
> @baoleai Is this "Sampling is executed during training" a data pipeline? which means when the first batch is being trained, the next batch is being sampled at the same time?

@baoleai @Seventeen17 @archwalker @alibaba-oss  I also want to ask this question.

**Comment by baoleai** [comment]
Yes, see GSL in user docs.
