### ISSUE TITLE
  When multiple PS servers are used, How to set parameter "emb_save_dir" when using multiple PS servers？

### ISSUE THREAD

**Issue by pangedeshijie** [alibaba/graph-learn#79]
I have specified the same local directory on each PS server, but the result is not good.
 Should this parameter be set to a public HDFS directory?

Thanks!

**Comment by jackonan** [comment]
Yes, a distributed file system is needed. You can launch a distributed program on a local machine, or mount NFS to local directory to establish a real distributed model.

Currently, HDFS is not supported.

**Comment by pangedeshijie** [comment]
@jackonan Thank you very much for your reply.
Currently, HDFS is not supported, **how can I use multiple PS？**

**Comment by baoleai** [comment]
Actually, save model to HDFS is supported by TensorFlow.
