### ISSUE TITLE
How to use the attributes of the edge?

### ISSUE THREAD

**Issue by chenshthu** [alibaba/graph-learn#80]
It seems that only weights work, and attributes are not used

**Comment by jackonan** [comment]
Try to traverse edges with attributes, ref to https://github.com/alibaba/graph-learn/blob/master/docs/graph_traverse_cn.md .

If edges are used in sampling, ref to GSL https://github.com/alibaba/graph-learn/blob/master/docs/gsl.md .

**Comment by Wellsjian** [comment]
i want to know too , can you solve this problem?
