### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by lzz0007** [alibaba/graph-learn#84]
Hi, 
I got this error message while installing the package on my mac. May I know what the root cause might be? Thanks.
_error: unable to open output file '/.../graph-learn/built/graphlearn/common/io/line_iterator.o': 'No such file or directory'_

**Comment by wuyifan18** [comment]
I have solved it. You just have to create the directory '/.../graph-learn/built/graphlearn/common/io/'.

**Comment by lzz0007** [comment]
> I have solved it. You just have to create the directory '/.../graph-learn/built/graphlearn/common/io/'.

Cool. Thanks!
