### ISSUE TITLE
sampling speed is much lower than training speed

### ISSUE THREAD

**Issue by LAwwp** [alibaba/graph-learn#87]
I tested graph-learn on a big graph in which there are 8M nodes and 100M edges. When I trained GraphSAGE model with batch_size = 1024, sample_num = [10, 25], I found that batch producing speed was too low. TensorFlow Profiler results indicated that "IteratorGetNext" op cost 95% of training time for each batch. I used 1 server and 1 worker in distributed mode and set tracker mode to 0. The server and the worker was deployed in the same machine so there were less network communication cost. Is this situation within our expectation of this system? 
I have had some try on speeding batch producing. Because of the sharing of grpc client, multithread methods of Dataset API could not work. But if I use multiprocess in python, segment fault will be caused after several iteration of training.

**Comment by jackonan** [comment]
Get your problems. The current 'batch producing' implementation, you can treat it as 'eager' mode. That is, each request costs a RPC procedure. In this way, you can run each request separately and check whether the data satisfy your expectation. In a typical GNN model, several such requests cooperate to generate training data. It is really slow on larger graphs. 

We will release the 'dag' mode runtime soon. That is, all the requests are organized as a DAG and executed in parallel. The data producing procedure will be pipelined with model training, which will accelerate up to 10x.

**Comment by baoleai** [comment]
You can use GSL in new version.
