### ISSUE TITLE
Student: Hello, I was wondering again how does a graph convolutional network convolute attributes of edges with attributes of nodes and the dimensions of the two attributes are different

### ISSUE THREAD

**Issue by Wellsjian** [alibaba/graph-learn#90]

**Comment by jackonan** [comment]
Here are some popular methods of processing edge attributes, which may be helpful to you.
1. Concat edge and node embedding after attributes vectorization.
2. Mapping edge attributes to embeddings, and then transform the embeddings into a WEIGHT, which will be used to enhance node embeddings.
