### ISSUE TITLE
Do the PS and workers of tensorflow have to be one-to-one in Deploy Mode 2.

### ISSUE THREAD

**Issue by Zdm-Jdsc-lalala** [alibaba/graph-learn#92]
If I use Deploy Mode 2 , 
do the PS and workers of tensorflow have to be one-to-one?  just like server and client.
Thank you for your answer！
@baoleai @archwalker @alibaba-oss

**Comment by jackonan** [comment]
Make sure the number of workers is not less than that of PS. More than one workers may connect to ONE PS.
And we suggest the number of workers can be divided by that of PS, to make load balance.

**Comment by Zdm-Jdsc-lalala** [comment]
Thank you for your answer! My main question is the use of Deploy Mode 2.
If there are 10 machines in our school, under the condition of using Deploy Mode 2 :
Can I use two machines as  independent  PS of TensorFlow, and the remaining 8 machines as one-to-one correspondence of server, client and TF worker? 
In other words, I have 2 separate TF PS, 8 servers, 8 clients and 8 TF workers.
Thank you for your answer！
@jackonan

**Comment by jackonan** [comment]
I think [this](https://github.com/alibaba/graph-learn/blob/master/docs/graph_object_cn.md#32-%E5%88%86%E5%B8%83%E5%BC%8F--server-mode) is what you need.
