### ISSUE TITLE
Different types of vertices have different attributes. How to train embedding?

### ISSUE THREAD

**Issue by pangedeshijie** [alibaba/graph-learn#93]
Thanks for open source graph learn！
My heterogeneous graph has three types of vertices: A, B, C.  A,B and C have different attributes.
Does aligraph support me to train embedding of A, B, and C in the same or different embedding space? 
If I use an supervised model, can I use it only for heterogeneous graphs? 

Thanks.

**Comment by jackonan** [comment]
Different types of nodes or edges indicate different meanings. Developers who design GNN model should care about this.
GL supports heterogeneous graphs. You may refer to the [Sampling](https://github.com/alibaba/graph-learn/blob/master/docs/graph_sampling_cn.md) doc, or [Bipartite GraphSage](https://github.com/alibaba/graph-learn/blob/master/examples/tf/bipartite_graphsage/README.md).
